import { ALL_SCENARIOS } from './data';

export const USE_CASES: string[] = [
  'Writing & Content', 
  'Research & Analysis', 
  'Productivity & Automation', 
  'Design & Creativity', 
  'Education & Learning', 
  'Programming'
];

export const AUDIENCES: string[] = [
  'Account Managers',
  'Apparel Brands',
  'Architects',
  'Artists',
  'Authors',
  'Backend Developers',
  'Businesses',
  'Chefs',
  'Consumers',
  'Corporate Trainers',
  'Crafters',
  'Creators',
  'Data Analysts',
  'Debate Club Members',
  'Designers',
  'Developers',
  'DevOps Engineers',
  'Digital Artists',
  'Educators',
  'Enterprise Developers',
  'Entrepreneurs',
  'Event Planners',
  'Executives',
  'Fashion Designers',
  'Filmmakers',
  'Food Bloggers',
  'Freelancers',
  'Frontend Developers',
  'Full-Stack Developers',
  'Game Masters',
  'Graphic Designers',
  'Health & Fitness',
  'History Students',
  'History Teachers',
  'Hobbyists',
  'Homeowners',
  'HR Professionals',
  'Indie Game Developers',
  'Indie Publishers',
  'Individuals',
  'Interior Designers',
  'Investors',
  'Job Seekers',
  'Journalists',
  'Marketers',
  'Math Teachers',
  'Music Students',
  'Music Theory Enthusiasts',
  'Parents',
  'Photographers',
  'Product Managers',
  'Professionals',
  'Project Managers',
  'QA Engineers',
  'Researchers',
  'Restaurants',
  'Sales Professionals',
  'Science Teachers',
  'Screenwriters',
  'Senior Developers',
  'Site Reliability Engineers',
  'Software Architects',
  'Startups',
  'Strategists',
  'Students',
  'System Admins',
  'Tattoo Artists',
  'Teachers',
  'Teams',
  'Tech Leads',
  'TTRPG Players',
  'Tutors',
  'Video Editors',
  'Video Producers',
  'Web Designers',
  'Writing Centers',
];

const allToolNames = ALL_SCENARIOS.flatMap(scenario => 
  scenario.tools.map(tool => tool.name)
);
const uniqueToolNames = [...new Set(allToolNames)];
const filteredToolNames = uniqueToolNames.filter(name => !name.startsWith('('));
export const TOOLS: string[] = filteredToolNames.sort((a, b) => a.localeCompare(b));
